export const LISTAR_MEDIDORES_REQUEST = 'LISTAR_MEDIDORES_REQUEST';
export const LISTAR_MEDIDORES_SUCCESS = 'LISTAR_MEDIDORES_SUCCESS';
export const LISTAR_MEDIDORES_FAILURE = 'LISTAR_MEDIDORES_FAILURE';

export const CREAR_MEDIDOR_REQUEST = 'CREAR_MEDIDOR_REQUEST';
export const CREAR_MEDIDOR_SUCCESS = 'CREAR_MEDIDOR_SUCCESS';
export const CREAR_MEDIDOR_FAILURE = 'CREAR_MEDIDOR_FAILURE';

export const ACTUALIZAR_MEDIDOR_REQUEST = 'ACTUALIZAR_MEDIDOR_REQUEST';
export const ACTUALIZAR_MEDIDOR_SUCCESS = 'ACTUALIZAR_MEDIDOR_SUCCESS';
export const ACTUALIZAR_MEDIDOR_FAILURE = 'ACTUALIZAR_MEDIDOR_FAILURE';

export const ELIMINAR_MEDIDOR_REQUEST = 'ELIMINAR_MEDIDOR_REQUEST';
export const ELIMINAR_MEDIDOR_SUCCESS = 'ELIMINAR_MEDIDOR_SUCCESS';
export const ELIMINAR_MEDIDOR_FAILURE = 'ELIMINAR_MEDIDOR_FAILURE';
