export const LISTAR_CLIENTES_REQUEST = 'LISTAR_CLIENTES_REQUEST';
export const LISTAR_CLIENTES_SUCCESS = 'LISTAR_CLIENTES_SUCCESS';
export const LISTAR_CLIENTES_FAILURE = 'LISTAR_CLIENTES_FAILURE';

export const CREAR_CLIENTE_REQUEST = 'CREAR_CLIENTE_REQUEST';
export const CREAR_CLIENTE_SUCCESS = 'CREAR_CLIENTE_SUCCESS';
export const CREAR_CLIENTE_FAILURE = 'CREAR_CLIENTE_FAILURE';

export const ACTUALIZAR_CLIENTE_REQUEST = 'ACTUALIZAR_CLIENTE_REQUEST';
export const ACTUALIZAR_CLIENTE_SUCCESS = 'ACTUALIZAR_CLIENTE_SUCCESS';
export const ACTUALIZAR_CLIENTE_FAILURE = 'ACTUALIZAR_CLIENTE_FAILURE';

export const ELIMINAR_CLIENTE_REQUEST = 'ELIMINAR_CLIENTE_REQUEST';
export const ELIMINAR_CLIENTE_SUCCESS = 'ELIMINAR_CLIENTE_SUCCESS';
export const ELIMINAR_CLIENTE_FAILURE = 'ELIMINAR_CLIENTE_FAILURE';
